### ISSUE TITLE
[bottomnavigationbar][Android] doesn't show at the bottom without heigh attribute

### ISSUE THREAD

**Issue by HamoBoker** [nativescript-community/ui-material-components#368]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Bottom navigation bar doesn't show in bottom without setting height attribute on android, 

works correctly on ios

### Which platform(s) does your issue occur on?
Android, tested on emulator v10, physical Device v8.0

### Please, provide the following version numbers that your issue occurs with:
```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.2.2 version and is up to date.
✔ Component @nativescript/core has 8.2.1 version and is up to date.
✔ Component @nativescript/ios has 8.2.1 version and is up to date.
✔ Component @nativescript/android has 8.2.2 version and is up to date.
```

```json
"dependencies": {
    "@nativescript-community/ui-material-bottom-navigation": "^7.0.1",
    "@nativescript-community/ui-material-bottomnavigationbar": "^7.0.1",
    "@nativescript-community/ui-material-bottomsheet": "^7.0.1",
    "@nativescript-community/ui-material-core": "^7.0.1",
    "@nativescript-community/ui-material-progress": "^7.0.1",
    "@nativescript-community/ui-material-snackbar": "^7.0.1",
    "@nativescript-community/ui-material-tabs": "^7.0.1",
    "@nativescript/core": "^8.2.1",
    "@nativescript/datetimepicker": "^2.1.9",
    "@nativescript/firebase-auth": "^1.0.6",
    "@nativescript/firebase-core": "^1.0.6",
    "@nativescript/firebase-crashlytics": "^1.0.6",
    "@nativescript/firebase-firestore": "^1.0.6",
    "@nativescript/localize": "^5.0.4",
    "@nativescript/tailwind": "^2.0.0",
    "@nativescript/theme": "~3.0.2",
    "@nstudio/nativescript-loading-indicator": "^4.1.2",
    "nativescript-drop-down": "^6.0.1",
    "nativescript-ui-listview": "^10.0.2",
    "nativescript-vue": "~2.9.1",
    "nativescript-vue-router-extended": "^1.1.8",
    "tailwindcss": "^3.0.23",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@mdi/font": "^6.5.95",
    "@nativescript/android": "8.2.2",
    "@nativescript/eslint-plugin": "^0.0.4",
    "@nativescript/ios": "8.2.1",
    "@nativescript/webpack": "~5.0.6",
    "@typescript-eslint/parser": "^5.14.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-vue": "^8.5.0",
    "nativescript-vue-template-compiler": "~2.9.1",
    "prettier": "^2.5.1",
    "scss-symbols-parser": "^2.0.1",
    "string-replace-loader": "^3.1.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Same code in Nativescript-Vue Example

### Is there any code involved? 
Tested code in Readme & Code Sample in demo-snippets
  
 (https://github.com/nativescript-community/ui-material-components/blob/master/demo-snippets/vue/BottomNavigationBar.vue)

**Comment by farfromrefug** [comment]
@HamoBoker fixed in 7.0.2

**Comment by Ombuweb** [comment]
I have v7.0.3 but it's not rendering at the bottom.

**Comment by HamoBoker** [comment]
Hi @Ombuweb , currently im using v7.0.2 and it works fine.

before v7.0.2 i set height attribute to 55

**Comment by Ombuweb** [comment]
Oh. I downgraded to v7.0.2 but still not rendering at the bottom.  Thanks for responding @HamoBoker.
